"""init_table

Revision ID: 98d787096fe9
Revises: 
Create Date: 2026-03-06 11:48:06.303854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98d787096fe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_points',
    sa.Column('city_name', sa.String(length=10), nullable=False, comment='設置縣市'),
    sa.Column('region_name', sa.String(length=20), nullable=False, comment='設置市區鄉鎮'),
    sa.Column('address', sa.String(length=100), nullable=False, comment='設置地點'),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=7), nullable=False, comment='經度'),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=7), nullable=False, comment='緯度'),
    sa.Column('direct', sa.String(length=20), nullable=False, comment='拍攝方向'),
    sa.Column('speed_limit', sa.Integer(), nullable=False, comment='速限'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否啟用'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新時間'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID主鍵'),
    sa.CheckConstraint('speed_limit >= 0', name='ck_camera_points_limit_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name', 'region_name', 'address', 'longitude', 'latitude', 'direct', name='uk_camera_points_location')
    )
    op.create_table('etl_runs',
    sa.Column('started_at', mysql.TIMESTAMP(fsp=6), nullable=False, comment='開始時間'),
    sa.Column('finished_at', mysql.TIMESTAMP(fsp=6), nullable=True, comment='結束時間'),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='etl_status_enum'), nullable=False, comment='執行狀態'),
    sa.Column('rows_fetched', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='取得資料數'),
    sa.Column('rows_inserted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='插入資料數'),
    sa.Column('rows_updated', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='更新資料數'),
    sa.Column('error_message', sa.String(length=255), nullable=True, comment='錯誤訊息'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID主鍵'),
    sa.CheckConstraint('finished_at >= started_at', name='ck_etl_speed_time_order'),
    sa.CheckConstraint('rows_fetched >= 0', name='ck_etl_rows_fetched_nonneg'),
    sa.CheckConstraint('rows_inserted >= 0', name='ck_etl_rows_inserted_nonneg'),
    sa.CheckConstraint('rows_updated >= 0', name='ck_etl_rows_updated_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_data',
    sa.Column('etl_run_id', sa.Integer(), nullable=False, comment='ETL執行批次ID'),
    sa.Column('city_name', sa.String(length=10), nullable=False, comment='設置縣市'),
    sa.Column('region_name', sa.String(length=20), nullable=False, comment='設置市區鄉鎮'),
    sa.Column('address', sa.String(length=100), nullable=False, comment='設置地點'),
    sa.Column('dept_name', sa.String(length=50), nullable=False, comment='管轄警局'),
    sa.Column('branch_name', sa.String(length=50), nullable=False, comment='管轄分局'),
    sa.Column('longitude', sa.String(length=20), nullable=False, comment='經度'),
    sa.Column('latitude', sa.String(length=20), nullable=False, comment='緯度'),
    sa.Column('direct', sa.String(length=20), nullable=False, comment='拍攝方向'),
    sa.Column('speed_limit', sa.String(length=10), nullable=False, comment='速限'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='匯入時間'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID主鍵'),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    op.drop_table('etl_runs')
    op.drop_table('camera_points')
    # ### end Alembic commands ###
